import { Gear } from '@/types';

interface CategoryInfo {
  name: string;
  description?: string;
}

interface CategoryData {
  info: CategoryInfo;
  gear: Gear[];
}

// Mock ürün verileri - Her kategori için özel ürünler
const categoryProducts: Record<string, CategoryData> = {
  'kamp-ocaklari': {
    info: {
      name: 'Kamp Ocakları',
      description: 'Doğada yemek pişirmek için ihtiyacınız olan tüm kamp ocakları. Portatif, güçlü ve dayanıklı seçenekler.',
    },
    gear: [
      {
        id: 'ocak-1',
        name: 'Gaz Kartuşlu Kamp Ocağı',
        description: 'Hafif ve taşınabilir gaz kartuşlu kamp ocağı. Hızlı ısınma ve düzenli alev.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 45,
        deposit: 120,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'ocak-2',
        name: 'Çift Alevli Kamp Ocağı',
        description: 'İki alevli profesyonel kamp ocağı. Aynı anda iki tencere pişirme imkanı.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 65,
        deposit: 180,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'ocak-3',
        name: 'Benzinli Kamp Ocağı',
        description: 'Yüksek performanslı benzinli kamp ocağı. Dondurucu soğuklarda bile çalışır.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800'],
        pricePerDay: 80,
        deposit: 250,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'ocak-4',
        name: 'Ultra Hafif Titan Ocağı',
        description: 'Sadece 85 gram! Ultra hafif titanyum kamp ocağı. Backpacking için ideal.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
        pricePerDay: 35,
        deposit: 100,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'termos': {
    info: {
      name: 'Termos ve Mug',
      description: 'Sıcak içeceklerinizi saatlerce sıcak tutan termoslar ve kamp için özel tasarlanmış muglar.',
    },
    gear: [
      {
        id: 'termos-1',
        name: 'Paslanmaz Çelik Termos 1L',
        description: '24 saat sıcaklık koruması. Paslanmaz çelik yapı, sızdırmaz kapak.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 25,
        deposit: 80,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'termos-2',
        name: 'Kamp Mug Seti 2\'li',
        description: 'İzolasyonlu çift cidarlı kamp mugları. Sıcak içecekler için ideal.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800'],
        pricePerDay: 15,
        deposit: 50,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'termos-3',
        name: 'Vakum İzolasyonlu Termos 750ml',
        description: 'Vakum izolasyon teknolojisi ile mükemmel sıcaklık koruması.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 30,
        deposit: 90,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'mutfak-setleri': {
    info: {
      name: 'Kamp Çatal Kaşık Bıçak Setleri',
      description: 'Kamp yemekleri için tasarlanmış çatal, kaşık ve bıçak setleri. Kompakt ve dayanıklı.',
    },
    gear: [
      {
        id: 'set-1',
        name: 'Paslanmaz Çelik Kamp Seti',
        description: '4 kişilik paslanmaz çelik çatal-kaşık-bıçak seti. Dayanıklı ve kolay temizlenir.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 20,
        deposit: 60,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'set-2',
        name: 'Katlanır Çatal-Bıçak Seti',
        description: 'Kompakt katlanır tasarım. Seyahat için mükemmel, az yer kaplar.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800'],
        pricePerDay: 18,
        deposit: 55,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'set-3',
        name: 'Titanyum Kamp Seti 2\'li',
        description: 'Ultra hafif titanyum malzeme. Backpacking için ideal, sadece 50 gram.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 25,
        deposit: 75,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'barbeku': {
    info: {
      name: 'Barbekü, Mangal ve Izgaralar',
      description: 'Açık havada lezzetli yemekler için mangal ve barbekü ekipmanları. Portatif ve pratik çözümler.',
    },
    gear: [
      {
        id: 'mangal-1',
        name: 'Katlanır Mangal 60cm',
        description: 'Kolay taşınabilir katlanır mangal. Kömür veya odun kullanımı için ideal.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 50,
        deposit: 150,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'mangal-2',
        name: 'Portatif Barbekü',
        description: 'Kompakt portatif barbekü. Izgara ve kapaklı tasarım, mükemmel ısı dağılımı.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800'],
        pricePerDay: 60,
        deposit: 180,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'mangal-3',
        name: 'Kamp Izgara Seti',
        description: 'Ayarlanabilir yükseklikte ızgara. Kömür tepsi ve toplayıcı dahil.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 45,
        deposit: 140,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'tencere-tava': {
    info: {
      name: 'Kamp Tenceresi ve Tava',
      description: 'Kamp yemekleri için özel tasarlanmış tencere ve tavalar. Hafif, dayanıklı ve kolay temizlenir.',
    },
    gear: [
      {
        id: 'tencere-1',
        name: 'Çelik Kamp Tenceresi Seti',
        description: '3 parçalı çelik tencere seti. Farklı boyutlarda, iç içe geçen tasarım.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 40,
        deposit: 120,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'tencere-2',
        name: 'Non-Stick Kamp Tavası',
        description: 'Yapışmaz kaplamalı kamp tavası. Kolay temizlenir, hafif ve dayanıklı.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800'],
        pricePerDay: 35,
        deposit: 100,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'tencere-3',
        name: 'Titanyum Tencere Seti',
        description: 'Ultra hafif titanyum tencere seti. Backpacking için mükemmel.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 55,
        deposit: 160,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'caydanlik': {
    info: {
      name: 'Kamp Çaydanlıkları',
      description: 'Doğada çay demlemek için özel kamp çaydanlıkları. Hızlı ısınma, ergonomik tasarım.',
    },
    gear: [
      {
        id: 'caydanlik-1',
        name: 'Paslanmaz Çelik Çaydanlık',
        description: '1.5L kapasiteli paslanmaz çelik çaydanlık. Hızlı kaynatma, dayanıklı yapı.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 25,
        deposit: 70,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'caydanlik-2',
        name: 'Kamp Çaydanlığı Kompakt',
        description: 'Kompakt tasarım kamp çaydanlığı. Seyahat için ideal, az yer kaplar.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800'],
        pricePerDay: 20,
        deposit: 60,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'kupa-bardak': {
    info: {
      name: 'Kupa Bardaklar',
      description: 'Kamp için özel tasarlanmış kupa ve bardaklar. İzolasyonlu, dayanıklı ve şık tasarım.',
    },
    gear: [
      {
        id: 'kupa-1',
        name: 'İzolasyonlu Kupa Seti 4\'lü',
        description: 'Çift cidarlı izolasyonlu kupalar. Sıcak içecekler için mükemmel, soğuk içecekler de soğuk kalır.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 18,
        deposit: 55,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'kupa-2',
        name: 'Kollapsible Kamp Kupa',
        description: 'Katlanabilir kamp kupası. Çok az yer kaplar, seyahat için ideal.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800'],
        pricePerDay: 12,
        deposit: 40,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'kupa-3',
        name: 'Paslanmaz Çelik Kupa',
        description: 'Dayanıklı paslanmaz çelik kupa. Isıyı korur, darbeye dayanıklı.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 15,
        deposit: 45,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'mutfak-diger': {
    info: {
      name: 'Diğer Kamp Mutfak Ürünleri',
      description: 'Kamp mutfağı için ihtiyacınız olan diğer ürünler. Kesme tahtaları, açacaklar, süzgeçler ve daha fazlası.',
    },
    gear: [
      {
        id: 'diger-1',
        name: 'Kamp Kesme Tahtası',
        description: 'Hafif ve kompakt kesme tahtası. Kolay temizlenir, katlanabilir tasarım.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 15,
        deposit: 45,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'diger-2',
        name: 'Kamp Mutfak Seti',
        description: 'Açacak, süzgeç, kaşık ve diğer mutfak gereçleri içeren kompakt set.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800'],
        pricePerDay: 20,
        deposit: 60,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'diger-3',
        name: 'Su Filtresi ve Sürahi',
        description: 'Kamp için su filtreleme sistemi. Temiz içme suyu garantisi.',
        category: 'cooking',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 30,
        deposit: 90,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'kamp-mobilyalari': {
    info: {
      name: 'Kamp Mobilyaları',
      description: 'Kamp alanınızda konfor ve pratiklik için tasarlanmış mobilyalar. Katlanabilir masalar, sandalyeler, tabureler ve kampetler.',
    },
    gear: [
      {
        id: 'masa-1',
        name: 'Katlanır Kamp Masası Alüminyum',
        description: 'Hafif alüminyum kamp masası. 4 kişilik, katlanır tasarım, kolay taşınır.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800'],
        pricePerDay: 40,
        deposit: 120,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'masa-2',
        name: 'Kompakt Kamp Masası Çelik',
        description: 'Dayanıklı çelik yapı, 6 kişilik geniş masa. Ayarlanabilir yükseklik.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800'],
        pricePerDay: 55,
        deposit: 150,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sandalye-1',
        name: 'Katlanır Kamp Sandalyesi',
        description: 'Konforlu kamp sandalyesi. Ergonomik tasarım, 120kg taşıma kapasitesi.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 25,
        deposit: 80,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sandalye-2',
        name: 'Sırt Desteği Kamp Sandalyesi',
        description: 'Yüksek sırt desteği olan kamp sandalyesi. Uzun süreli oturma için ideal.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800'],
        pricePerDay: 30,
        deposit: 90,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'tabure-1',
        name: 'Kamp Taburesi Alüminyum',
        description: 'Hafif alüminyum kamp taburesi. Kompakt ve dayanıklı.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 18,
        deposit: 55,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'kampet-1',
        name: 'Kampet - Kamp Yatak',
        description: 'Rahat kamp yatağı. Şişirilebilir, kompakt taşıma çantası dahil.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
        pricePerDay: 35,
        deposit: 100,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'kampet-2',
        name: 'Premium Kampet Seti',
        description: 'Çift kişilik kampet seti. Yüksek konfor, otomatik şişirme sistemi.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800'],
        pricePerDay: 65,
        deposit: 180,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'aydinlatma-ve-fenerler': {
    info: {
      name: 'Aydınlatma ve Fenerler',
      description: 'Kamp alanınızı aydınlatmak için ihtiyacınız olan tüm aydınlatma çözümleri. Kamp fenerleri ve lambaları.',
    },
    gear: [
      {
        id: 'fener-1',
        name: 'LED Kamp Feneri Güçlü',
        description: '2000 lümen güçlü LED kamp feneri. Su geçirmez, uzun batarya ömrü.',
        category: 'lighting',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 20,
        deposit: 60,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'fener-2',
        name: 'Kafa Feneri LED',
        description: 'Eller serbest kullanım için kafa feneri. 3 mod ayarı, hafif ve ergonomik.',
        category: 'lighting',
        images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800'],
        pricePerDay: 15,
        deposit: 45,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'fener-3',
        name: 'Portatif Güneş Enerjili Fener',
        description: 'Güneş enerjisi ile şarj olan kamp feneri. Çevre dostu, uzun kullanım.',
        category: 'lighting',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 25,
        deposit: 70,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'lamba-1',
        name: 'LED Kamp Lambası',
        description: 'Çadır içi kullanım için LED kamp lambası. Dimmer özelliği, uzun batarya ömrü.',
        category: 'lighting',
        images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800'],
        pricePerDay: 18,
        deposit: 55,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'lamba-2',
        name: 'Asılı Kamp Lambası',
        description: 'Çadır tavanına asılabilir kamp lambası. Yumuşak ışık, USB şarj.',
        category: 'lighting',
        images: ['https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800'],
        pricePerDay: 22,
        deposit: 65,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'lamba-3',
        name: 'Gaz Lambası Klasik',
        description: 'Geleneksel gaz lambası. Romantik atmosfer, uzun yanma süresi.',
        category: 'lighting',
        images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
        pricePerDay: 30,
        deposit: 85,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'isitici-ve-sobalar': {
    info: {
      name: 'Isıtıcı ve Sobalar',
      description: 'Soğuk kamp gecelerinde sıcak kalmanızı sağlayacak ısıtıcı ve soba çözümleri. Çadır sobaları, LPG sobaları ve portatif sobalar.',
    },
    gear: [
      {
        id: 'cadir-soba-1',
        name: 'Çadır Sobası Döküm',
        description: 'Döküm çadır sobası. Uzun süreli ısıtma, güvenli kullanım, baca sistemi dahil.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 120,
        deposit: 400,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'cadir-soba-2',
        name: 'Portatif Çadır Sobası',
        description: 'Hafif ve taşınabilir çadır sobası. Çelik yapı, kolay montaj.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800'],
        pricePerDay: 90,
        deposit: 300,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'lpg-soba-1',
        name: 'LPG Tüp Sobası 3KW',
        description: 'Güçlü LPG sobası. Termostatlı, güvenlik sensörü, hızlı ısıtma.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 70,
        deposit: 220,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'lpg-soba-2',
        name: 'Katalitik LPG Sobası',
        description: 'Oksijen sensörlü katalitik soba. Güvenli, verimli, düşük yakıt tüketimi.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800'],
        pricePerDay: 80,
        deposit: 250,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'portatif-soba-1',
        name: 'Portatif Gaz Sobası',
        description: 'Küçük ve kompakt portatif soba. Kartuşlu, hızlı kurulum.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800'],
        pricePerDay: 50,
        deposit: 150,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'portatif-soba-2',
        name: 'Elektrikli Portatif Isıtıcı',
        description: 'Elektrikli portatif ısıtıcı. Fanlı, termostatlı, güvenlik kilitli.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
        pricePerDay: 45,
        deposit: 130,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  // Alt kategoriler - Kamp Mobilyaları
  'kamp-masasi': {
    info: {
      name: 'Kamp Masası',
      description: 'Kamp alanınızda yemek yemek ve eşyalarınızı düzenlemek için ihtiyacınız olan kamp masaları. Hafif, katlanabilir ve dayanıklı seçenekler.',
    },
    gear: [
      {
        id: 'masa-1',
        name: 'Katlanır Kamp Masası Alüminyum',
        description: 'Hafif alüminyum kamp masası. 4 kişilik, katlanır tasarım, kolay taşınır.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800'],
        pricePerDay: 40,
        deposit: 120,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'masa-2',
        name: 'Kompakt Kamp Masası Çelik',
        description: 'Dayanıklı çelik yapı, 6 kişilik geniş masa. Ayarlanabilir yükseklik.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800'],
        pricePerDay: 55,
        deposit: 150,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'masa-3',
        name: 'Kamp Masası Portatif',
        description: 'Ultra hafif portatif kamp masası. Backpacking için ideal, sadece 2 kg.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 35,
        deposit: 100,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'kamp-sandalyesi': {
    info: {
      name: 'Kamp Sandalyesi',
      description: 'Kamp alanında rahatça oturabilmek için kamp sandalyeleri. Ergonomik tasarım, katlanabilir ve taşınabilir.',
    },
    gear: [
      {
        id: 'sandalye-1',
        name: 'Katlanır Kamp Sandalyesi',
        description: 'Konforlu kamp sandalyesi. Ergonomik tasarım, 120kg taşıma kapasitesi.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 25,
        deposit: 80,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sandalye-2',
        name: 'Sırt Desteği Kamp Sandalyesi',
        description: 'Yüksek sırt desteği olan kamp sandalyesi. Uzun süreli oturma için ideal.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800'],
        pricePerDay: 30,
        deposit: 90,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'sandalye-3',
        name: 'Kamp Sandalyesi Ultra Hafif',
        description: 'Sadece 850 gram! Ultra hafif kamp sandalyesi. Kompakt ve dayanıklı.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 22,
        deposit: 70,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'kamp-taburesi': {
    info: {
      name: 'Kamp Taburesi',
      description: 'Pratik ve hafif kamp tabureleri. Az yer kaplar, kolay taşınır.',
    },
    gear: [
      {
        id: 'tabure-1',
        name: 'Kamp Taburesi Alüminyum',
        description: 'Hafif alüminyum kamp taburesi. Kompakt ve dayanıklı.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 18,
        deposit: 55,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'tabure-2',
        name: 'Kamp Taburesi Çelik',
        description: 'Dayanıklı çelik yapı, 150kg taşıma kapasitesi. Süngerli oturma yüzeyi.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
        pricePerDay: 20,
        deposit: 60,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'kampet': {
    info: {
      name: 'Kampet',
      description: 'Kamp yatakları ve kampetler. Rahat uyku için şişirilebilir yatak seçenekleri.',
    },
    gear: [
      {
        id: 'kampet-1',
        name: 'Kampet - Kamp Yatak',
        description: 'Rahat kamp yatağı. Şişirilebilir, kompakt taşıma çantası dahil.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
        pricePerDay: 35,
        deposit: 100,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'kampet-2',
        name: 'Premium Kampet Seti',
        description: 'Çift kişilik kampet seti. Yüksek konfor, otomatik şişirme sistemi.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800'],
        pricePerDay: 65,
        deposit: 180,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'kampet-3',
        name: 'Self-Inflating Kamp Matı',
        description: 'Otomatik şişen kamp matı. Isı izolasyonu, kompakt tasarım.',
        category: 'furniture',
        images: ['https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800'],
        pricePerDay: 28,
        deposit: 85,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  // Alt kategoriler - Aydınlatma ve Fenerler
  'kamp-fenerleri': {
    info: {
      name: 'Kamp Fenerleri',
      description: 'Kamp alanınızı aydınlatmak için güçlü ve pratik kamp fenerleri. LED teknolojisi ile uzun ömürlü ışık kaynağı.',
    },
    gear: [
      {
        id: 'fener-1',
        name: 'LED Kamp Feneri Güçlü',
        description: '2000 lümen güçlü LED kamp feneri. Su geçirmez, uzun batarya ömrü.',
        category: 'lighting',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 20,
        deposit: 60,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'fener-2',
        name: 'Kafa Feneri LED',
        description: 'Eller serbest kullanım için kafa feneri. 3 mod ayarı, hafif ve ergonomik.',
        category: 'lighting',
        images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800'],
        pricePerDay: 15,
        deposit: 45,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'fener-3',
        name: 'Portatif Güneş Enerjili Fener',
        description: 'Güneş enerjisi ile şarj olan kamp feneri. Çevre dostu, uzun kullanım.',
        category: 'lighting',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 25,
        deposit: 70,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'fener-4',
        name: 'Kamp Feneri El Feneri',
        description: 'Kompakt el feneri. Yüksek parlaklık, uzun menzil, su geçirmez.',
        category: 'lighting',
        images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800'],
        pricePerDay: 18,
        deposit: 55,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'kamp-lambalari': {
    info: {
      name: 'Kamp Lambaları',
      description: 'Çadır içi ve kamp alanı aydınlatması için kamp lambaları. Yumuşak ışık, uzun batarya ömrü.',
    },
    gear: [
      {
        id: 'lamba-1',
        name: 'LED Kamp Lambası',
        description: 'Çadır içi kullanım için LED kamp lambası. Dimmer özelliği, uzun batarya ömrü.',
        category: 'lighting',
        images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800'],
        pricePerDay: 18,
        deposit: 55,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'lamba-2',
        name: 'Asılı Kamp Lambası',
        description: 'Çadır tavanına asılabilir kamp lambası. Yumuşak ışık, USB şarj.',
        category: 'lighting',
        images: ['https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800'],
        pricePerDay: 22,
        deposit: 65,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'lamba-3',
        name: 'Gaz Lambası Klasik',
        description: 'Geleneksel gaz lambası. Romantik atmosfer, uzun yanma süresi.',
        category: 'lighting',
        images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
        pricePerDay: 30,
        deposit: 85,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'lamba-4',
        name: 'Kamp Lambası Portatif',
        description: 'Taşınabilir kamp lambası. Çoklu modlar, uzun ömürlü batarya.',
        category: 'lighting',
        images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800'],
        pricePerDay: 20,
        deposit: 60,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  // Alt kategoriler - Isıtıcı ve Sobalar
  'cadir-sobalari': {
    info: {
      name: 'Çadır Sobaları',
      description: 'Çadır içinde kullanım için özel tasarlanmış sobalar. Güvenli ısıtma, baca sistemi ile havalandırma.',
    },
    gear: [
      {
        id: 'cadir-soba-1',
        name: 'Çadır Sobası Döküm',
        description: 'Döküm çadır sobası. Uzun süreli ısıtma, güvenli kullanım, baca sistemi dahil.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=800'],
        pricePerDay: 120,
        deposit: 400,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'cadir-soba-2',
        name: 'Portatif Çadır Sobası',
        description: 'Hafif ve taşınabilir çadır sobası. Çelik yapı, kolay montaj.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800'],
        pricePerDay: 90,
        deposit: 300,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'cadir-soba-3',
        name: 'Mini Çadır Sobası',
        description: 'Küçük çadırlar için kompakt soba. Verimli yanma, güvenlik özellikleri.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 75,
        deposit: 250,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'lpg-tup-sobalari': {
    info: {
      name: 'LPG Tüp Sobaları',
      description: 'LPG tüpü ile çalışan güçlü ısıtıcılar. Termostatlı, güvenlik sensörlü, hızlı ısıtma.',
    },
    gear: [
      {
        id: 'lpg-soba-1',
        name: 'LPG Tüp Sobası 3KW',
        description: 'Güçlü LPG sobası. Termostatlı, güvenlik sensörü, hızlı ısıtma.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800'],
        pricePerDay: 70,
        deposit: 220,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'lpg-soba-2',
        name: 'Katalitik LPG Sobası',
        description: 'Oksijen sensörlü katalitik soba. Güvenli, verimli, düşük yakıt tüketimi.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800'],
        pricePerDay: 80,
        deposit: 250,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'lpg-soba-3',
        name: 'LPG Sobası Portatif',
        description: 'Hafif portatif LPG sobası. Hızlı kurulum, termostat kontrolü.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800'],
        pricePerDay: 65,
        deposit: 200,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  'portatif-sobalar': {
    info: {
      name: 'Portatif Sobalar',
      description: 'Küçük ve taşınabilir soba çözümleri. Gaz kartuşlu veya elektrikli seçenekler.',
    },
    gear: [
      {
        id: 'portatif-soba-1',
        name: 'Portatif Gaz Sobası',
        description: 'Küçük ve kompakt portatif soba. Kartuşlu, hızlı kurulum.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800'],
        pricePerDay: 50,
        deposit: 150,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'portatif-soba-2',
        name: 'Elektrikli Portatif Isıtıcı',
        description: 'Elektrikli portatif ısıtıcı. Fanlı, termostatlı, güvenlik kilitli.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800'],
        pricePerDay: 45,
        deposit: 130,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'portatif-soba-3',
        name: 'Mini Portatif Soba',
        description: 'Ultra kompakt portatif soba. Küçük çadırlar için ideal, güvenli kullanım.',
        category: 'other',
        images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800'],
        pricePerDay: 40,
        deposit: 120,
        available: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
};

export const categoryService = {
  getCategoryGear(slug: string): CategoryData {
    const normalizedSlug = slug.toLowerCase();
    const data = categoryProducts[normalizedSlug];
    
    if (!data) {
      return {
        info: { name: 'Kategori Bulunamadı' },
        gear: [],
      };
    }
    
    return data;
  },

  getAllCategorySlugs(): string[] {
    return Object.keys(categoryProducts);
  },

  getAllGear(): Gear[] {
    const allGear: Gear[] = [];
    Object.values(categoryProducts).forEach((categoryData) => {
      allGear.push(...categoryData.gear);
    });
    return allGear;
  },

  getGearById(id: string): Gear | null {
    const allGear = this.getAllGear();
    return allGear.find(g => g.id === id) || null;
  },
};

