export const config = {
  apiBaseUrl: import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api',
  appName: import.meta.env.VITE_APP_NAME || 'CampScape',
  appDescription: import.meta.env.VITE_APP_DESCRIPTION || 'Doğada unutulmaz kamp deneyimleri için kamp alanları ve kiralık kamp malzemeleri',
  enableDarkMode: true,
  itemsPerPage: 12,
  imagePlaceholder: '/placeholder-image.jpg',
  defaultAvatar: '/default-avatar.png',
} as const;

export const breakpoints = {
  mobile: '320px',
  tablet: '768px',
  desktop: '1024px',
} as const;

export const routes = {
  home: '/',
  blog: '/blog',
  blogDetails: '/blog/:id',
  gear: '/gear',
  gearDetails: '/gear/:id',
  category: '/category/:categorySlug',
  search: '/search',
  about: '/about',
  references: '/references',
  contact: '/contact',
  faq: '/faq',
  favorites: '/favorites',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  profile: '/profile',
  admin: '/admin',
  adminCampsites: '/admin/campsites',
  adminAddCampsite: '/admin/campsites/add',
  adminEditCampsite: '/admin/campsites/edit/:id',
  adminGear: '/admin/gear',
  adminAddGear: '/admin/gear/add',
  adminEditGear: '/admin/gear/edit/:id',
  adminBlogs: '/admin/blogs',
  adminAddBlog: '/admin/blogs/add',
  adminEditBlog: '/admin/blogs/edit/:id',
  adminCategories: '/admin/categories',
  adminAddCategory: '/admin/categories/add',
  adminEditCategory: '/admin/categories/edit/:id',
  adminMessages: '/admin/messages',
  adminNewsletters: '/admin/newsletters',
  adminAppointments: '/admin/appointments',
  adminBrands: '/admin/brands',
  adminColors: '/admin/colors',
  adminReferenceBrands: '/admin/reference-brands',
  adminReferenceImages: '/admin/reference-images',
  adminChangePassword: '/admin/change-password',
  adminUserOrders: '/admin/user-orders',
  adminReviews: '/admin/reviews',
  adminAnalytics: '/admin/analytics',
  adminUsers: '/admin/users',
} as const;

